[package]
name = "tikv-bench"
version = "0.0.1"
publish = false

[[bin]]
name = "tikv-bench"
path = "bin/bench-tikv.rs"

[[test]]
name = "benches"
path = "benches.rs"

[dependencies]
clap = "2"
crossbeam-channel = "0.2"
log = "0.3.9"
mio = "0.5"
protobuf = "~2.0"
raft = "0.3"
rand = "0.3"
tempdir = "0.3"
serde_json = "1.0"

[dependencies.tikv-lib]
path = ".."

[dependencies.tikv-test]
path = "../tikv_tests"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"

[dependencies.tipb]
git = "https://github.com/pingcap/tipb.git"
