[package]
name = "backup"
version = "0.0.1"
edition = "2018"
publish = false

[[test]]
name = "integrations"
path = "tests/integrations/mod.rs"

[features]
default = ["protobuf-codec"]
protobuf-codec = [
	"engine/protobuf-codec",
	"engine_rocks/protobuf-codec",
	"engine_traits/protobuf-codec",
	"external_storage/protobuf-codec",
	"grpcio/protobuf-codec",
	"keys/protobuf-codec",
	"kvproto/protobuf-codec",
	"raft/protobuf-codec",
	"tidb_query/protobuf-codec",
	"tikv/protobuf-codec",
	"tikv_util/protobuf-codec",
	"txn_types/protobuf-codec",
]
prost-codec = [
	"engine/prost-codec",
	"engine_rocks/prost-codec",
	"engine_traits/prost-codec",
	"external_storage/prost-codec",
	"grpcio/prost-codec",
	"keys/prost-codec",
	"kvproto/prost-codec",
	"raft/prost-codec",
	"tidb_query/prost-codec",
	"tikv/prost-codec",
	"tikv_util/prost-codec",
	"txn_types/prost-codec",
]

[dependencies]
crc64fast = "0.1"
engine = { path = "../engine", default-features = false }
engine_rocks = { path = "../engine_rocks", default-features = false }
engine_traits = { path = "../engine_traits", default-features = false }
external_storage = { path = "../external_storage", default-features = false }
failure = "0.1"
futures = "0.1"
grpcio = { version = "0.5.0-alpha.5", features = [ "openssl-vendored" ], default-features = false }
hex = "0.3"
keys = { path = "../keys", default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
raft = { version = "0.6.0-alpha", default-features = false }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tidb_query = { path = "../tidb_query", default-features = false }
tikv = { path = "../../", default-features = false }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util", default-features = false }
tokio-threadpool = "0.1"
txn_types = { path = "../txn_types", default-features = false }

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "d919ccd35976b9b84b8d03c07138c1cc05a36087"
default-features = false
features = ["nightly", "push", "process"]

[dev-dependencies]
rand = "0.7"
tempfile = "3.0"
test_util = { path = "../test_util", default-features = false }
test_raftstore = { path = "../test_raftstore", default-features = false }
uuid = { version = "0.7", features = [ "serde", "v4" ] }
