[package]
name = "raftengine"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
protobuf = "~2.0"
quick-error = "1.2.2"
serde = "1.0"
serde_derive = "1.0"
tikv_util = { path = "../tikv_util" }
crc32c = "0.4.0"
log = { version = "0.3", features = ["max_level_trace", "release_max_level_debug"] }
compress = "0.1.2"
raft = "0.4"
byteorder = "1.2"
errno = "0.2.4"
libc = "0.2"
tempfile = "3.0"
lazy_static = "1.3"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
version = "0.1.4"
default-features = false