[package]
name = "pd_client"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.3"
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
slog-term = "2.4"
quick-error = "1.2.2"
protobuf = "2"
lazy_static = "1.3"
futures = "0.1"
tikv_alloc = { path = "../tikv_alloc", default-features = false }
tokio-core = "0.1"
tokio-timer = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
grpcio = { version = "0.5.0-alpha.3", features = [ "secure" ] }
keys = { path = "../keys" }
tikv_util = { path = "../tikv_util" }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
hex = "0.3"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "b668f3911d6569de2e1e8b2672fccec1cc8298be"
features = ["nightly", "push", "process"]
