[package]
name = "cdc"
version = "4.0.0-alpha"
license = "Apache-2.0"
homepage = "https://tikv.org"
repository = "https://github.com/tikv/tikv/"
readme = "README.md"
edition = "2018"
publish = false

[features]
default = ["no_validate", "protobuf-codec"]
no_validate = []
protobuf-codec = [
  "engine_rocks/protobuf-codec",
  "grpcio/protobuf-codec",
  "kvproto/protobuf-codec",
  "pd_client/protobuf-codec",
  "tikv/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "engine_rocks/prost-codec",
  "grpcio/prost-codec",
  "kvproto/prost-codec",
  "pd_client/prost-codec",
  "tikv/prost-codec",
  "txn_types/prost-codec",
]

[dependencies]
engine_rocks = { path = "../engine_rocks", default-features = false }
failure = "0.1"
futures = "0.1"
grpcio = { version = "0.5.0-alpha.3", features = [ "openssl-vendored" ], default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
pd_client = { path = "../pd_client", default-features = false }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tikv = { path = "../../", default-features = false }
tikv_util = { path = "../tikv_util" }
tokio-threadpool = "0.1"
txn_types = { path = "../txn_types", default-features = false }

[dev-dependencies]
tempfile = "3.0"
test_util = { path = "../test_util" }
test_raftstore = { path = "../test_raftstore", default-features = false }
