[package]
name = "codec"
version = "0.0.1"
publish = false

[lib]
path = "lib.rs"

[dependencies]
byteorder = "1.2"
quick-error = "1.2"

[dev-dependencies]
protobuf = "2.0"
bytes = "0.4.10"
rand = "0.5"
