[package]
name = "tikv"
version = "0.0.1"
keywords = ["KV", "distributed-systems", "raft"]

[lib]
name = "tikv"

[[bin]]
name = "server"

[dependencies]
log = "0.3"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"
