[package]
name = "tikv"
version = "0.0.1"
keywords = ["KV", "distributed-systems", "raft"]

[lib]
name = "tikv"

[[bin]]
name = "server"

[dependencies]
log = "0.3"
rocksdb = "0.3"
byteorder = "0.4"
mio = "0.5"
rand = "0.3"
quick-error = "0.2"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"
