[workspace]
members = [
  "src",
  "src/tikv_bin",
  "src/tikv_tests",
  "src/tikv_benches",
  "src/fuzz"
]

[profile.dev]
codegen-units = 4

[profile.release]
debug = true
lto = true
# TODO: remove this once rust-lang/rust#50199 is resolved.
codegen-units = 2

[profile.bench]
debug = true
lto = false
