[package]
name = "tikv"
version = "0.0.1"
keywords = ["KV", "distributed-systems", "raft"]

[lib]
name = "tikv"

[[bin]]
name = "tikv-server"

[[bin]]
name = "bench-tikv"
path = "benches/bin/bench-tikv.rs"

[[test]]
name = "tests"

[[test]]
name = "benches"
path = "benches/benches.rs"

[dependencies]
log = "0.3"
byteorder = "0.4"
rand = "0.3"
mio = "0.5"
quick-error = "0.2"
tempdir = "0.3"
getopts = "0.2"
uuid = "0.1"
time = "0.1"
clippy = "*"

[dependencies.rocksdb]
git = "https://github.com/ngaut/rust-rocksdb.git"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto"

[dependencies.tipb]
git = "https://github.com/pingcap/tipb.git"

[dev-dependencies]
env_logger = "0.3"

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 3
debug = true
