[package]
name = "tikv"
version = "4.0.0-alpha"
authors = ["The TiKV Authors"]
description = "A distributed transactional key-value database powered by Rust and Raft"
license = "Apache-2.0"
keywords = ["KV", "distributed-systems", "raft"]
homepage = "https://tikv.org"
repository = "https://github.com/tikv/tikv/"
readme = "README.md"
edition = "2018"
publish = false

[features]
tcmalloc = ["tikv_alloc/tcmalloc"]
jemalloc = ["tikv_alloc/jemalloc", "engine/jemalloc", "engine_rocks/jemalloc"]
mimalloc = ["tikv_alloc/mimalloc"]
portable = ["engine/portable"]
sse = ["engine/sse"]
mem-profiling = ["tikv_alloc/mem-profiling"]
failpoints = ["fail/failpoints"]
prost-codec = [
  "tipb/prost-codec",
  "kvproto/prost-codec",
  "grpcio/prost-codec",
  "raft/prost-codec",
  "engine/prost-codec",
  "tikv_util/prost-codec",
]
protobuf-codec = [
  "tipb/protobuf-codec",
  "kvproto/protobuf-codec",
  "grpcio/protobuf-codec",
  "raft/protobuf-codec",
]

[lib]
name = "tikv"

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = { version = "2.3", default-features = false }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
slog-term = "2.4"
slog_derive = "0.1"
byteorder = "1.2"
bytes = "0.4.12"
rand = "0.6.5"
quick-error = "1.2.2"
tempfile = "3.0"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc32fast = "1.2"
crc64fast = "0.1"
fs2 = "0.4"
spin = "0.5"
protobuf = "2.8"
nix = "0.11"
utime = "0.2"
chrono = "0.4"
lazy_static = "1.3"
backtrace = "0.3.9"
url = "2"
sys-info = "0.5.7"
futures = "0.1"
futures-cpupool = "0.1"
futures-locks = "0.1"
tokio-core = "0.1"
tokio-timer = "0.2"
tokio-executor = "0.1"
tokio-sync = "0.1.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
zipf = "5.0.1"
bitflags = "1.0.1"
fail = "0.3"
uuid = { version = "0.7", features = [ "serde", "v4" ] }
grpcio = { version = "0.5.0-alpha.5", features = [ "openssl-vendored" ], default-features = false }
raft = { version = "0.6.0-alpha" , default-features = false }
crossbeam = "0.7.2"
derive_more = "0.15.0"
hex = "0.3"
more-asserts = "0.1"
hyper = { version = "0.12", default-features = false, features = ["runtime"] }
tokio-threadpool = "0.1.13"
tokio-fs = "0.1.6"
tokio-io = "0.1.12"
vlog = "0.1.4"
mime = "0.3.13"
failure = "0.1"
prost = "0.5.0"
regex = "1.3"
rev_lines = "0.2.1"
nom = "5.0.1"
derive-new = "0.5"
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }

tikv_alloc = { path = "components/tikv_alloc", default-features = false }
tikv_util = { path = "components/tikv_util" }
test_util = { path = "components/test_util" }
log_wrappers = { path = "components/log_wrappers" }
engine = { path = "components/engine" }
tidb_query = { path = "components/tidb_query" }
pd_client = { path = "components/pd_client" }
keys = { path = "components/keys" }
engine_traits = { path = "components/engine_traits" }
sst_importer = { path = "components/sst_importer" }
engine_rocks = { path = "components/engine_rocks" }
codec = { path = "components/codec" }

[dependencies.murmur3]
git = "https://github.com/pingcap/murmur3.git"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "b668f3911d6569de2e1e8b2672fccec1cc8298be"
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "b668f3911d6569de2e1e8b2672fccec1cc8298be"

[dev-dependencies]
panic_hook = { path = "components/panic_hook" }
test_sst_importer = { path = "components/test_sst_importer" }

[replace]
# TODO: remove this when new raft-rs is published.
"raft:0.6.0-alpha" = { git = "https://github.com/pingcap/raft-rs", branch = "master", default-features = false }
"raft-proto:0.6.0-alpha" = { git = "https://github.com/pingcap/raft-rs", branch = "master", default-features = false }
"protobuf:2.8.0" = { git = "https://github.com/nrc/rust-protobuf", branch = "v2.8" }
"protobuf-codegen:2.8.0" = { git = "https://github.com/nrc/rust-protobuf", branch = "v2.8" }
"prost:0.5.0" = { git = "https://github.com/danburkert/prost", rev = "1944c27c3029d01ff216e7b126d846b6cf8c7d77" }

[target.'cfg(unix)'.dependencies]
signal = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs" }
criterion-papi = "0.1"
pprof = { version = "0.3", features = ["flamegraph", "protobuf"] }

[workspace]
members = [
  "fuzz",
  "fuzz/fuzzer-afl",
  "fuzz/fuzzer-libfuzzer",
  "fuzz/fuzzer-honggfuzz",
  "tests",
  "components/test_raftstore",
  "components/test_storage",
  "components/test_coprocessor",
  "components/test_sst_importer",
  "components/test_util",
  "components/tikv_alloc",
  "components/match_template",
  "components/codec",
  "components/panic_hook",
  "components/tipb_helper",
  "components/log_wrappers",
  "components/tikv_util",
  "components/tidb_query",
  "components/tidb_query_datatype",
  "components/tidb_query_codegen",
  "components/pd_client",
  "components/external_storage",
  "components/backup",
  "components/keys",
  "components/sst_importer",
  "cmd",
]
default-members = ["cmd"]

[profile.dev]
opt-level = 0
debug = 1 # required for line numbers in tests, see tikv #5049
codegen-units = 4
lto = false
incremental = true
panic = 'abort'
debug-assertions = false
overflow-checks = false
rpath = false

[profile.release]
opt-level = 3
debug = false
codegen-units = 1
lto = "thin"
incremental = false
panic = 'abort'
debug-assertions = false
overflow-checks = false
rpath = false

[profile.test]
opt-level = 0
debug = 1 # enable line numbers by default for easy test debugging
codegen-units = 16
lto = false
incremental = true
debug-assertions = true
overflow-checks = true
rpath = false

# The benchmark profile is identical to release, except that lto = false
[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false
