[package]
name = "memory_trace_macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
tikv_alloc = { path = "../tikv_alloc" }
