[package]
name = "error_code"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
raft = { version = "0.6.0-alpha", default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-4.0", default-features = false }
tikv_alloc = { path = "../tikv_alloc" }
