[package]
name = "log_wrappers"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
slog = "2.3"
slog-term = "2.4"
hex = "0.3"
kvproto = { version = "0.0.1", git = "https://github.com/pingcap/kvproto.git", rev = "11e0e6d3aacf889552c897fbf2ae290a1d6ecc9e" }
tikv_alloc = { path = "../tikv_alloc", default-features = false }
