[package]
name = "encryption"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "engine_traits/protobuf-codec",
  "error_code/protobuf-codec",
  "kvproto/protobuf-codec",
  "tikv_util/protobuf-codec",
]
prost-codec = [
  "engine_traits/prost-codec",
  "error_code/prost-codec",
  "kvproto/prost-codec",
  "tikv_util/prost-codec",
]
failpoints = ["fail/failpoints"]

[dependencies]
byteorder = "1.2"
bytes = "0.5"
crossbeam = "0.7"
configuration = { path = "../configuration" }
crc32fast = "1.2"
engine_traits = { path = "../engine_traits", default-features = false }
error_code = { path = "../error_code", default-features = false }
fail = "0.4"
failure = "0.1"
file_system = { path = "../file_system" }
futures = "0.3"
lazy_static = "1.3"
prometheus = { version = "0.10", features = ["nightly"] }
futures-util = { version = "0.3", default-features = false, features = ["std", "io"] }
hex = "0.4.2"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
openssl = "0.10"
protobuf = "2.8"
rand = "0.7"
rusoto_core = "0.45.0"
rusoto_credential = "0.45.0"
rusoto_kms = { version = "0.45.0", features = ["serialize_structs"] }
rusoto_util = { path = "../rusoto_util" }
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util", default-features = false }
tokio = { version = "0.2", features = ["time", "rt-core"] }

[dev-dependencies]
matches = "0.1.8"
tempfile = "3.1"
toml = "0.5"
rusoto_mock = "0.45.0"
rust-ini = "0.14.0"
structopt = "0.3"
