[package]
name = "tikv_util"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
<<<<<<< HEAD
hashbrown = { version = "0.1", features = ["serde"] }
log = { version = "0.3", features = ["max_level_trace", "release_max_level_debug"] }
=======
async-speed-limit = "0.3"
backtrace = "0.3.9"
byteorder = "1.2"
codec = { path = "../codec" }
configuration = { path = "../configuration" }
chrono = "0.4"
crc32fast = "1.2"
crossbeam = "0.7.2"
fail = "0.3"
fs2 = "0.4"
futures = "0.1"
futures03 = { package = "futures", version = "0.3" }
fxhash = "0.2.1"
grpcio = { version = "0.5", default-features = false, features = ["openssl-vendored"] }
hex = "0.4"
lazy_static = "1.3"
libc = "0.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
openssl = "0.10"
prometheus = { version = "0.8", features = ["nightly", "push"] }
quick-error = "1.2.2"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
>>>>>>> 7d13ca0... *: reduce sys_getdents syscall (#7306)
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.3"
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
slog-term = "2.4"
byteorder = "1.2"
rand = "0.6.5"
quick-error = "1.2.2"
tempdir = "0.3"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc = "1.8"
protobuf = "~2.0"
utime = "0.2"
chrono = "0.4"
lazy_static = "0.2.1"
backtrace = "0.2.3"
url = "1.7.2"
regex = "1.0"
indexmap = { version = "1.0", features = ["serde-1"] }
futures = "0.1"
futures-cpupool = "0.1"
tikv_alloc = { path = "../tikv_alloc" }
tokio-core = "0.1"
tokio-timer = "0.2"
tokio-executor = "0.1"
tokio-threadpool = "0.1.13"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
grpcio = { version = "0.4", features = [ "secure" ] }
crossbeam = "0.5"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
version = "0.1.4"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs" }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }
raft = "0.4"

[[bench]]
name = "channel"
path = "benches/channel/mod.rs"
