[package]
name = "fuzz-targets"
version = "0.0.1"
publish = false
edition = "2018"

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "tidb_query/protobuf-codec",
  "tikv_util/protobuf-codec",
]
prost-codec = [
  "tidb_query/protobuf-codec",
  "tikv_util/prost-codec",
]

[lib]
path = "mod.rs"

[dependencies]
byteorder = "1"
failure = "0.1"
tidb_query = { path = "../../components/tidb_query", default-features = false }
tikv_util = { path = "../../components/tikv_util", default-features = false }
