[package]
name = "resolved_ts"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = ["txn_types/protobuf-codec"]
prost-codec = ["txn_types/prost-codec"]

[dependencies]
hex = "0.3"
tikv_util = { path = "../tikv_util" }
txn_types = { path = "../txn_types", default-features = false }
