[server]
# set listening address.
addr = "127.0.0.1:20160"
# if not set, use addr instead. set advertise listening address for client communication.
advertise-addr = "127.0.0.1:20161"
# set which dsn to use, warning: default is rocksdb without persistent.
dsn = "rocksdb"
# set the path to rocksdb directory.
store = "/tmp/tikv/store"
# log level: trace, debug, info, warn, error, off.
log-level = "info"

[metric]
# There are two type of statsd client implemented: `log` and `udp. The default statsd client is
# `log` which will output to log.
# log level: trace, debug, info, warn, error, off.
level = "off"
# if log level is off then `udp` will be activated.
# remote statsd server address.
host = "127.0.0.1:8125"
# local statsd client address.
addr = "127.0.0.1:8989"
# metric prefix: trace, debug, info, warn, error, off.
prefix = "tikv"

[raft]
# set cluster id, must greater than 0.
#cluster-id = 1
# set pd address, host:port
#pd = 