[package]
name = "tikv-bin"
version = "2.1.0-beta"
build = "build.rs"
publish = false

[build-dependencies]
time = "0.1"

[lib]
name = "tikv_bin"
path = "lib.rs"

[[bin]]
name = "tikv-server"
path = "tikv-server.rs"

[[bin]]
name = "tikv-ctl"
path = "tikv-ctl.rs"

[[bin]]
name = "tikv-fail"
path = "tikv-fail.rs"

[[bin]]
name = "tikv-importer"
path = "tikv-importer.rs"

[dependencies]
clap = "2"
libc = "0.2"
rustc-serialize = "0.3"
chrono = "0.4"
log = "0.3.9"
slog = "2.2"
slog-async = "2.3"
slog-term = "2.4"
grpcio = { version = "0.3", features = [ "secure" ] }
toml = "0.4"
futures = "0.1"
protobuf = "~2.0"
raft = "0.3"
fs2 = "0.4"
serde_json = "1.0"

[dependencies.tikv-lib]
path = ".."

[target.'cfg(unix)'.dependencies]
nix = "0.9.0"
signal = "0.4"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"

[dependencies.jemallocator]
git = "https://github.com/busyjay/jemallocator.git"
branch = "dev"
features = ["profiling"]
optional = true
