[package]
name = "profiler"
version = "0.0.1"
edition = "2018"
publish = false

[features]
profiling = ["lazy_static", "cpuprofiler", "callgrind", "valgrind_request"]

[dependencies]
tikv_alloc = { path = "../tikv_alloc", default-features = false }

[target.'cfg(unix)'.dependencies]
lazy_static = { version = "1.3.0", optional = true }
cpuprofiler = { version = "0.0.3", optional = true }
callgrind = { version = "1.1.0", optional = true }
valgrind_request = { version = "1.1.0", optional = true }

[[example]]
name = "prime"
required-features = ["profiling"]
