[package]
name = "tracer"
version = "0.1.0"
edition = "2018"

[dependencies]
crossbeam = "0.7"
pin-project = "0.4"
tracer-attribute = { path = "./tracer-attribute" }
tikv_alloc = { path = "../tikv_alloc" }
snowflake = "1.2"

[dependencies.futures_01]
version = "0.1"
package = "futures"

[dependencies.futures_03]
version = "0.3.1"
package = "futures"

[dev-dependencies]
criterion = "0.3"
crossbeam = "0.7"

[[bench]]
name = "tracer"
harness = false