[package]
name = "tracer"
version = "0.0.1"
edition = "2018"

[dev-dependencies]
criterion = "0.3"
minitrace = { git = "https://github.com/zhongzc/minitrace.git" }

[[bench]]
name = "tracer"
harness = false