[package]
name = "tracer"
version = "0.0.1"
edition = "2018"

[dev-dependencies]
criterion = "0.3"
tikv_util = { path = "../tikv_util" }
tracing = "0.1.13"
tracing-core = "0.1.10"
tracing-subscriber = "0.2.3"

[dependencies.minitrace_cmp]
package = "minitrace"
git = "https://github.com/zhongzc/minitrace.git"
branch = "dev"

[dependencies.minitrace]
git = "https://github.com/zhongzc/minitrace.git"

[[bench]]
name = "tracer"
harness = false