[package]
name = "into_other"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "engine_traits/protobuf-codec",
  "kvproto/protobuf-codec",
  "raft/protobuf-codec"
]
prost-codec = [
  "engine_traits/prost-codec",
  "kvproto/prost-codec",
  "raft/prost-codec"
]

[dependencies]
engine_traits = { path = "../engine_traits", default-features = false }
kvproto = { rev = "f42e582bf0bb6bc2aee647e5f4126d51ccf6d377", git = "https://github.com/pingcap/kvproto.git", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }
