[package]
name = "into_other"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "engine_traits/protobuf-codec",
  "kvproto/protobuf-codec",
  "raft/protobuf-codec"
]
prost-codec = [
  "engine_traits/prost-codec",
  "kvproto/prost-codec",
  "raft/prost-codec"
]

[dependencies]
engine_traits = { path = "../engine_traits", default-features = false }
<<<<<<< HEAD
kvproto = { rev = "7a046020d1c091638e1e8aba623c8c1e8962219d", git = "https://github.com/pingcap/kvproto.git", default-features = false }
=======
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
>>>>>>> 586ed074e... Remove commit of kvproto for every Cargo.toml (#10478)
raft = { version = "0.6.0-alpha", default-features = false }
