[package]
name = "into_other"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "engine_traits/protobuf-codec",
  "kvproto/protobuf-codec",
  "raft/protobuf-codec"
]
prost-codec = [
  "engine_traits/prost-codec",
  "kvproto/prost-codec",
  "raft/prost-codec"
]

[dependencies]
engine_traits = { path = "../engine_traits", default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false, rev="511a3225c29f9272af83d28efed92eba835cd34f" }
raft = { version = "0.6.0-alpha", default-features = false }
