[package]
name = "file_system"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
crc32fast = "1.2"
lazy_static = "1.3"
openssl = "0.10"

[dev-dependencies]
rand = "0.7"
tempfile = "3.0"
