[package]
name = "file_system"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
collections = { path = "../collections" }
crc32fast = "1.2"
fs2 = "0.4"
lazy_static = "1.3"
openssl = "0.10"
tikv_alloc = { path = "../tikv_alloc" }
engine_traits = { path = "../engine_traits" }

[dev-dependencies]
rand = "0.7"
tempfile = "3.0"
