[package]
name = "file_system"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
crc32fast = "1.2"
futures = "0.3"
fs2 = "0.4"
lazy_static = "1.3"
libc = "0.2"
openssl = "0.10"
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
time = "0.1"
tokio = { version = "0.2", features = ["time", "sync"] }

[dev-dependencies]
rand = "0.7"
tempfile = "3.0"
