[package]
name = "raft_log_engine"
version = "0.0.1"
publish = false
edition = "2018"

[features]
protobuf-codec = [
  "keys/protobuf-codec",
  "raft/protobuf-codec",
  "kvproto/protobuf-codec",
]

prost-codec = [
  "keys/prost-codec",
  "raft/prost-codec",
  "kvproto/prost-codec",
]

[dependencies]
engine_traits = { path = "../engine_traits" }
tikv_util = { path = "../tikv_util" }
hex = "0.4"
keys = { path = "../keys" }
num_cpus = "1"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
lazy_static = "1.4.0"
time = "0.1"
configuration = { path = "../configuration" }
tempfile = "3.0"
serde = "1.0"
serde_derive = "1.0"
coarsetime = "0.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }
raft-engine = { git = "https://github.com/tikv/raft-engine"}
protobuf = "2"
