[package]
name = "tidb_query_common"
version = "0.0.1"
edition = "2018"
publish = false
description = "Common utility of a query engine to run TiDB pushed down executors"

[dependencies]
hex = "0.3"
rand = "0.6.5"
time = "0.1"
failure = "0.1"
derive_more = "0.15.0"
tikv_util = { path = "../tikv_util" }
#tidb_query_datatype = { path = "../tidb_query_datatype" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
prometheus = { version = "0.8", features = ["nightly", "push", "process"] }
lazy_static = "1.3"
coarsetime = "0.1"

[dependencies.prometheus-static-metric]
git = "https://github.com/tikv/rust-prometheus.git"
rev = "4b445b20ca1b0aa3f79c35b4885dc3ba716d30e0"

[dev-dependencies]
byteorder = "1.2"

