[package]
name = "tidb_query_common"
version = "0.0.1"
edition = "2018"
publish = false
description = "Common utility of a query engine to run TiDB pushed down executors"

[features]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
derive_more = "0.99.3"
failure = "0.1"
hex = "0.4"
lazy_static = "1.3"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
prometheus = { version = "0.8", features = ["nightly", "push", "process"] }
rand = "0.7"
tikv_util = { path = "../tikv_util" }
time = "0.1"

[dependencies.prometheus-static-metric]
git = "https://github.com/tikv/rust-prometheus.git"
rev = "d919ccd35976b9b84b8d03c07138c1cc05a36087"

[dev-dependencies]
byteorder = "1.2"
