[package]
name = "cmd"
version = "0.0.1"
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
default = ["tikv/default"]
tcmalloc = ["tikv/tcmalloc"]
jemalloc = ["tikv/jemalloc"]
portable = ["tikv/portable"]
sse = ["tikv/sse"]
mem-profiling = ["tikv/mem-profiling"]
profiling = ["tikv/profiling"]
no-fail = ["tikv/no-fail"]

[lib]
name = "cmd"

[[bin]]
name = "tikv-server"

[[bin]]
name = "tikv-ctl"

[[bin]]
name = "tikv-importer"

[dependencies]
tikv = { path = "../", default-features = false }
log = { version = "0.3", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
rand = "0.6.5"
toml = "0.4"
libc = "0.2"
fs2 = "0.4"
protobuf = "2"
nix = "0.11"
chrono = "0.4"
clap = "2.32"
url = "1.7.2"
futures = "0.1"
<<<<<<< HEAD
serde = "1.0"
=======
futures-cpupool = "0.1"
grpcio = { version = "0.5", default-features = false, features = ["openssl-vendored"] }
hex = "0.4"
keys = { path = "../components/keys" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
libc = "0.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
nix = "0.11"
pd_client = { path = "../components/pd_client" }
prometheus = { version = "0.8", features = ["nightly", "push"] }
protobuf = "2.8"
raft = { version = "0.6.0-alpha", default-features = false }
raftstore = { path = "../components/raftstore" }
rand = "0.7"
>>>>>>> 7d13ca0... *: reduce sys_getdents syscall (#7306)
serde_json = "1.0"
fail = "0.3"
grpcio = { version = "0.5", features = [ "openssl-vendored" ] }
raft = "0.4.3"
hex = "0.3"
vlog = "0.1.4"
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-3.1" }
tikv_util = { path = "../components/tikv_util" }
engine = { path = "../components/engine" }
tikv_alloc = { path = "../components/tikv_alloc" }
backup = { path = "../components/backup" }

[target.'cfg(unix)'.dependencies]
signal = "0.6"
