[package]
name = "trace_pb"
version = "0.0.1"
edition = "2018"

[features]
default = []
protobuf-codec = ["protobuf-build/protobuf-codec"]
prost-codec = ["prost", "prost-derive", "lazy_static", "protobuf-build/prost-codec"]

[dependencies]
minitrace = { git = "https://github.com/zhongzc/minitrace.git", branch = "busy" }
protobuf = "2"
prost = { version = "0.6", optional = true }
prost-derive = { version = "0.6", optional = true }
lazy_static = { version = "1.3", optional = true }

[build-dependencies]
protobuf-build = { version = "0.11.0", default-features = false }
