[package]
name = "tracing_protobuf"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
name = "tracing_protobuf"
path = "src/lib.rs"

[dependencies]
protobuf = "=2.8.0"
tikv_alloc = { path = "../tikv_alloc" }

[build-dependencies]
protobuf-build = { version = "0.11", default-features = false }
