[package]
name = "keys"
version = "0.1.0"
edition = "2018"
publish = false

[features]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
byteorder = "1.2"
derive_more = "0.99.3"
failure = "0.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
log_wrappers = { path = "../log_wrappers" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }
