[package]
name = "keys"
version = "0.1.0"
edition = "2018"
publish = false

[features]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
byteorder = "1.2"
hex = "0.4"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
thiserror = "1.0"
tikv_alloc = { path = "../tikv_alloc" }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }
