[package]
name = "engine_rocks"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = ["engine/protobuf-codec"]
prost-codec = ["engine/prost-codec"]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]

[dependencies]
engine = { path = "../engine", default-features = false }
engine_traits = { path = "../engine_traits" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }

[dependencies.rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
package = "rocksdb"

[dev-dependencies]
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
tempfile = "3.0"
