[package]
name = "engine_rocks"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
	"engine/protobuf-codec",
	"engine_traits/protobuf-codec",
	"kvproto/protobuf-codec",
	"tikv_util/protobuf-codec",
]
prost-codec = [
	"engine/prost-codec",
	"engine_traits/prost-codec",
	"kvproto/prost-codec",
	"tikv_util/prost-codec",
]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]

[dependencies]
engine = { path = "../engine", default-features = false }
engine_traits = { path = "../engine_traits", default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util", default-features = false }

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
package = "rocksdb"

[dev-dependencies]
tempfile = "3.0"
