[package]
name = "tidb_query_codegen"
version = "0.0.1"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
darling = "0.9"
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
heck = "0.3"
