[package]
name = "tracer_pb"
version = "0.1.0"
edition = "2018"

[features]
default = []
protobuf-codec = ["protobuf-build/protobuf-codec"]
prost-codec = ["prost", "prost-derive", "lazy_static", "protobuf-build/prost-codec"]

[lib]
name = "tracer_pb"

[dependencies]
tracer = { path = "../tracer" }
protobuf = "2"
prost = { version = "0.6", optional = true }
prost-derive = { version = "0.6", optional = true }
lazy_static = { version = "1.3", optional = true }

[build-dependencies]
protobuf-build = { version = "0.11.0", default-features = false }
