[package]
name = "tikv-server"
version = "0.0.1"
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
tcmalloc = ["tikv/tcmalloc"]
jemalloc = ["tikv/jemalloc"]
mimalloc = ["tikv/mimalloc"]
portable = ["tikv/portable"]
sse = ["tikv/sse"]
mem-profiling = ["tikv/mem-profiling"]
failpoints = ["tikv/failpoints"]
protobuf-codec = ["tikv/protobuf-codec",]
prost-codec = ["tikv/prost-codec"]

[dependencies]
clap = "2.32"
server = { path = "../../components/server" }
tikv = { path = "../../", default-features = false }
toml = "0.4"
