[package]
name = "raftstore"
version = "0.0.1"
authors = ["The TiKV Authors"]
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
failpoints = ["fail/failpoints"]
prost-codec = [
  "prost",
  "tipb/prost-codec",
  "kvproto/prost-codec",
  "grpcio/prost-codec",
  "raft/prost-codec",
  "engine/prost-codec",
  "tikv_util/prost-codec",
  "sst_importer/prost-codec",
  "pd_client/prost-codec",
]
protobuf-codec = [
  "tipb/protobuf-codec",
  "kvproto/protobuf-codec",
  "grpcio/protobuf-codec",
  "raft/protobuf-codec",
  "sst_importer/protobuf-codec",
  "pd_client/protobuf-codec",
]
testexport = []

[dependencies]
batch-system = { path = "../batch-system" }
bitflags = "1.0.1"
byteorder = "1.2"
bytes = "0.4.12"
configuration = { path = "../configuration" }
crc32fast = "1.2"
crossbeam = "0.7.2"
engine = { path = "../engine" }
engine_rocks = { path = "../engine_rocks" }
engine_traits = { path = "../engine_traits" }
fail = "0.3"
fs2 = "0.4"
futures = "0.1"
futures-executor = "0.3.1"
futures-util = { version = "0.3.1", default-features = false, features = ["io"] }
grpcio = { version = "0.5.0-alpha.5", features = [ "openssl-vendored" ], default-features = false }
hex = "0.3"
keys = { path = "../keys" }
txn_types = { path = "../txn_types" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
log_wrappers = { path = "../log_wrappers" }
pd_client = { path = "../pd_client" }
prost = { version = "0.5.0", optional = true }
protobuf = "2.8"
quick-error = "1.2.2"
raft = { version = "0.6.0-alpha" , default-features = false }
rand = "0.6.5"
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
sst_importer = { path = "../sst_importer" }
tempfile = "3.0"
tidb_query = { path = "../tidb_query", default-features = false }
tikv_alloc = { path = "../tikv_alloc", default-features = false }
tikv_util = { path = "../tikv_util" }
time = "0.1"
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
tokio = { version = "0.2", features = ["sync"] }
tokio-core = "0.1"
tokio-executor = "0.1"
tokio-threadpool = "0.1.13"
tokio-timer = "0.2"
url = "2"
uuid = { version = "0.7", features = [ "serde", "v4" ] }

[dependencies.prometheus]
git = "https://github.com/tikv/rust-prometheus.git"
rev = "d919ccd35976b9b84b8d03c07138c1cc05a36087"
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
git = "https://github.com/tikv/rust-prometheus.git"
rev = "d919ccd35976b9b84b8d03c07138c1cc05a36087"

[dependencies.yatp]
git = "https://github.com/tikv/yatp.git"

[dev-dependencies]
panic_hook = { path = "../panic_hook" }
test_sst_importer = { path = "../test_sst_importer" }
