[package]
name = "external_storage"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
futures-io = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
futures-executor = "0.3"
rand = "0.7"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tikv_alloc = { path = "../tikv_alloc" }
url = "2.0"

[dev-dependencies]
tempfile = "3.1"
