[package]
name = "external_storage"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
futures-io = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
futures-executor = "0.3"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
tempfile = "3.0"
rand = "0.6.5"
url = "2.0"
tikv_alloc = { path = "../tikv_alloc", default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "release-3.1", default-features = false }
