[package]
name = "test_raftstore"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv_util = { path = "../tikv_util" }
tikv = { path = "../../", default-features = false }
tempfile = "3.0"
kvproto = { path = "../../../kvproto" }
raft = { git = "https://github.com/pingcap/raft-rs", rev = "eeaee89a4eba7aa17abd630388df2f1c3a0f76ad" }
futures = "0.1"
tokio-timer = "0.2"
tokio-threadpool = "0.1"
grpcio = { version = "0.5.0-alpha.1", features = [ "secure", "prost-codec" ] }
rand = "0.6.5"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
engine = { path = "../engine" }
hex = "0.3"
