[package]
name = "test_storage"
version = "0.0.1"
publish = false

[dependencies]
tikv = { path = "../../" }
test_raftstore = { path = "../test_raftstore" }
kvproto = { path = "../kvproto" }
futures = "0.1"
