[package]
name = "test_storage"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv = { path = "../../", default-features = false }
test_raftstore = { path = "../test_raftstore" }
kvproto = { git = "https://github.com/youjiali1995/kvproto.git", branch="pessimistic-dev" }
futures = "0.1"
