[package]
name = "test_storage"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv_util = { path = "../tikv_util" }
tikv = { path = "../../", default-features = false }
test_raftstore = { path = "../test_raftstore" }
kvproto = { version = "0.0.1", git = "https://github.com/pingcap/kvproto.git", rev = "1aa667dafd66c97f755f825d6f824bc3f1ac1a55" }
futures = "0.1"
