[package]
name = "test_storage"
version = "0.0.1"
publish = false

[lib]
path = "lib.rs"

[dependencies]
tikv = { path = "../../" }
test_raftstore = { path = "../test_raftstore" }
futures = "0.1"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"
