[package]
name = "test_storage"
version = "0.0.1"
publish = false

[dependencies]
tikv = { path = "../../" }
test_raftstore = { path = "../test_raftstore" }
futures = "0.1"

[dependencies.kvproto]
git = "https://github.com/zhangjinpeng1987/kvproto.git"
branch = "prewrite-not-exist"
