[package]
name = "fuzzer-libfuzzer"
version = "0.0.1"
publish = false
build = "../fuzzer_build.rs"

[dependencies]
fuzz-targets = {path = "../targets"}
libfuzzer-sys = {git = "https://github.com/rust-fuzz/libfuzzer-sys.git"}
