[package]
name = "fuzzer-libfuzzer"
version = "0.0.1"
publish = false

[dependencies]
fuzz-targets = {path = "../targets"}
libfuzzer-sys = {git = "https://github.com/rust-fuzz/libfuzzer-sys.git", rev = "4594b1f3" }
