[package]
name = "multi_level_pool"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
futures = "0.3.1"
crossbeam  = "0.7.2"
dashmap = "1.2.0"
num_cpus = "1.2.0"
rand = "0.7.2"
lazy_static = "1.4.0"
parking_lot = "0.9.0"
tokio-sync = "0.2.0-alpha.6"
tokio01-sync = { package = "tokio-sync", version = "0.1.7" }
futures01 = { package = "futures", version = "0.1.29" }
tokio-executor = "0.2.0-alpha.6"
tokio-timer = "0.3.0-alpha.6"
init_with = "1.1.0"
derive-new = "0.5"

tikv_util = { path = "../tikv_util" }

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "b668f3911d6569de2e1e8b2672fccec1cc8298be"
features = ["nightly", "push", "process"]