[package]
name = "test_coprocessor"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv_util = { path = "../tikv_util" }
tikv = { path = "../../", default-features = false }
tipb = { version = "0.0.1", git = "https://github.com/pingcap/tipb.git", rev = "af5d98495e746cc38f83b23be2ea4b3e4b2c437f" }
kvproto = { version = "0.0.1", git = "https://github.com/pingcap/kvproto.git", rev = "1aa667dafd66c97f755f825d6f824bc3f1ac1a55" }
protobuf = "~2.0"
test_storage = { path = "../test_storage" }
futures = "0.1"
