[package]
name = "test_coprocessor"
version = "0.0.1"
publish = false

[dependencies]
tikv = { path = "../../" }
tipb = { path = "../tipb" }
kvproto = { path = "../kvproto" }
protobuf = "~2.0"
test_storage = { path = "../test_storage" }
futures = "0.1"
