[package]
name = "test_coprocessor"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
	"kvproto/protobuf-codec",
	"test_storage/protobuf-codec",
	"tikv/protobuf-codec",
	"tikv_util/protobuf-codec",
	"tipb/protobuf-codec",
	"txn_types/protobuf-codec",
]
prost-codec = [
	"kvproto/prost-codec",
	"test_storage/prost-codec",
	"tikv/prost-codec",
	"tikv_util/prost-codec",
	"tipb/prost-codec",
	"txn_types/prost-codec",
]

[dependencies]
futures = "0.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
protobuf = "2"
test_storage = { path = "../test_storage", default-features = false }
tidb_query = { path = "../tidb_query", default-features = false }
tikv = { path = "../../", default-features = false }
tikv_util = { path = "../tikv_util", default-features = false }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
txn_types = { path = "../txn_types", default-features = false }
